spring.web.locale-resolver=accept-header
spring.messages.fallback-to-system-locale=false
spring.messages.basename=messages

spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/club
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.show-sql=true

management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=*

management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=0.99
info.app.description=Application serving information about teams and players